--liquibase formatted sql

--changeset Andrei:1
CREATE TABLE USER_ACCOUNT_ROLES(
    USER_ROLE_ID    INT(10)     PRIMARY KEY AUTO_INCREMENT,
    NAME            VARCHAR(55) NOT NULL,
    CONSTRAINT uq_user_account_roles_name UNIQUE (NAME)
);

--changeset Andrei:2
CREATE TABLE USER_ACCOUNTS(
    USERNAME        VARCHAR(25)   NOT NULL PRIMARY KEY,
    PASSWORD        VARCHAR(255)   NOT NULL,
    USER_ROLE_ID    INT(10)        NOT NULL,
    CONSTRAINT fk_user_accounts_user_account_roles_id FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ACCOUNT_ROLES (USER_ROLE_ID)
);

--changeset Andrei:3
CREATE TABLE USER_ACCOUNT_DETAILS(
    USERNAME    VARCHAR (25)   NOT NULL PRIMARY KEY,
    FIRST_NAME  VARCHAR (55)    NOT NULL,
    LAST_NAME   VARCHAR (65)    NOT NULL,
    EMAIL       VARCHAR (255)   NOT NULL,
    CONSTRAINT fk_user_account_details_user_accounts FOREIGN KEY (USERNAME) REFERENCES USER_ACCOUNTS(USERNAME)
);

--changeset Andrei:4
CREATE TABLE NOT_ACTIVATED_ACCOUNTS(
    USERNAME    VARCHAR (25)    NOT NULL PRIMARY KEY,
    TOKEN       VARCHAR (260)   NOT NULL,
    CONSTRAINT  uq_not_activated_accounts_token  UNIQUE (TOKEN),
    CONSTRAINT fk_not_activated_accounts_user_accounts FOREIGN KEY (USERNAME) REFERENCES USER_ACCOUNTS(USERNAME)
);

--changeset Andrei:5
CREATE TABLE REFRESH_TOKENS(
    USERNAME    VARCHAR (25)    NOT NULL,
    TOKEN       VARCHAR (255)   NOT NULL,
    CONSTRAINT fk_refresh_tokens_user_accounts FOREIGN KEY (USERNAME) REFERENCES USER_ACCOUNTS(USERNAME),
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (USERNAME,TOKEN)
);

--changeset Andrei:6
INSERT INTO USER_ACCOUNT_ROLES (NAME) VALUE ('ACTIVATED_ACCOUNT'), ('NOT_ACTIVATED_ACCOUNT');