spring:
  #spring cloud properties
  cloud:
    config:
      enabled: false
  #datasource properties
  datasource:
    url: @user.db.url@
    driver-class-name: @db.driverClassName@
    username: @db.username@
    password: @db.password@
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  #jpa properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL5Dialect
  #liquibase configurations
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

#eureka configurations
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false