export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const GET_ALL_DEVICES = "GET_ALL_DEVICES";
export const ADD_DEVICE = "ADD_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";
export const GET_ALL_DEVICES_FROM_CACHE = "GET_ALL_DEVICES_FROM_CACHE";
