-- liquibase formatted sql

-- changeset Andrei:1
CREATE TABLE CONSTANTS
(
    CONSTANT_NAME  VARCHAR(45) PRIMARY KEY,
    CONSTANT_VALUE BIGINT(18) NOT NULL
);

-- changeset Andrei:2
INSERT INTO CONSTANTS(CONSTANT_NAME, CONSTANT_VALUE)
VALUES ('UNREGISTERED_DEVICE_INDEX', 1);

-- changeset Andrei:3
CREATE TABLE UNREGISTERED_DEVICES
(
    ID                  VARCHAR(255) PRIMARY KEY,
    NAME                VARCHAR(50)  NOT NULL,
    STATE               VARCHAR(25)  NOT NULL,
    TOKEN               VARCHAR(255) NOT NULL,
    PAIRING_PASSWORD    VARCHAR(25),
    USER_TRYING_TO_PAIR VARCHAR(45),
    ID_AFTER_PAIRING    VARCHAR(255)
);

-- changeset Andrei:4
CREATE TABLE DEVICE_SETTINGS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIME_INTERVAL INT(10)     NOT NULL,
    NAME          VARCHAR(50) NOT NULL
);

-- changeset Andrei:5
CREATE TABLE DEVICES
(
    DEVICE_CODE        VARCHAR(255) PRIMARY KEY,
    DELETED            BOOLEAN DEFAULT 0,
    OWNER_USERNAME     VARCHAR(45) NOT NULL,
    DEVICE_SETTINGS_ID BIGINT      NOT NULL,
    REGISTERED_ON      BIGINT      NOT NULL,
    CONSTRAINT fk_devices_device_settings FOREIGN KEY (DEVICE_SETTINGS_ID) REFERENCES DEVICE_SETTINGS (ID)
);